name:                pf2048
version:             0.1.0.0
github:              "colindbrown/pf2048"
license:             BSD3
author:              "Colin Brown and Jonathan Rich"
maintainer:          "example@example.com"
copyright:           "2019 Colin Brown and Jonathan Rich"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/colindbrown/pf2048#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  pf2048-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -O2
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    dependencies:
    - pf2048

tests:
  pf2048-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - pf2048
